hmrc/gform

- app/uk/gov/hmrc/bforms/core/FormValidator.scala
- app/uk/gov/hmrc/bforms/core/TemplateValidator.scala
- app/uk/gov/hmrc/bforms/models/ComponentType.scala
- app/uk/gov/hmrc/bforms/models/FieldValue.scala
- app/uk/gov/hmrc/bforms/services/PdfGenerator.scala
- app/uk/gov/hmrc/bforms/services/SubmissionService.scala
- sample-data/template.json
- test/uk/gov/hmrc/bforms/core/FormValidatorSpec.scala
- test/uk/gov/hmrc/bforms/core/TemplateValidatorSpec.scala
- test/uk/gov/hmrc/bforms/core/parsers/ValueParserSpec.scala
- test/uk/gov/hmrc/bforms/models/ExprSpec.scala
- test/uk/gov/hmrc/bforms/models/FieldValueSpec.scala
- test/uk/gov/hmrc/bforms/services/FormServiceSpec.scala
- test/uk/gov/hmrc/bforms/services/PdfGeneratorSpec.scala
- test/uk/gov/hmrc/bforms/services/SubmissionServiceSpec.scala
Total option on text component and submitMode option that does readonly and info
> Dave/eeitt 847/text ii

- app/uk/gov/hmrc/bforms/core/FormValidator.scala
- app/uk/gov/hmrc/bforms/models/ComponentType.scala
- app/uk/gov/hmrc/bforms/models/ComponentTypeRaw.scala
- app/uk/gov/hmrc/bforms/models/FieldValue.scala
- app/uk/gov/hmrc/bforms/services/SubmissionService.scala
- test/uk/gov/hmrc/bforms/models/FieldValueGroupRawSpec.scala
mandatory and submit mode in group fields pending (see test)
> allow templates with groups to store to Mongo. Support for 

- project/MicroServiceBuild.scala
so that builds to the right bintray repo for service-manager
> Change app name to gform

- conf/application.conf
- test/uk/gov/hmrc/gform/services/PdfGeneratorSpec.scala
N.b. You will need to upload your schema and template again, to the new DB
> Change mongo db name to gform, and one other change in the pdf spec

- app/uk/gov/hmrc/gform/models/Section.scala
- app/uk/gov/hmrc/gform/services/FormService.scala
- sample-data/schema.json
- test/uk/gov/hmrc/gform/core/FormValidatorSpec.scala
- test/uk/gov/hmrc/gform/core/TemplateValidatorSpec.scala
- test/uk/gov/hmrc/gform/core/parsers/ValueParserSpec.scala
- test/uk/gov/hmrc/gform/services/FormServiceSpec.scala
- test/uk/gov/hmrc/gform/services/SubmissionServiceSpec.scala
The gform-frontend was also modified, branch with the same name.
> New shortName field added to Section

- app/uk/gov/hmrc/gform/ApplicationLoader.scala
- it/uk/gov/hmrc/gform/PingSpec.scala
- it/uk/gov/hmrc/gform/support/ITSpec.scala
- it/uk/gov/hmrc/gform/support/ITSpecBase.scala
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/gform/Spec.scala
Now the `sbt it:test` makes sense.
This is the first step towards integration testing which test all components wired and running. At the moment only /ping/ping was tested but later we can test as well more complicated functionalities.
> first IT Spec

- sample-data/template.json
This fix is required for  EEITT-1078 in the frontend
> EEITT-1078 - Replace dots in input names and ids to something HTML-compliant

- app/uk/gov/hmrc/gform/models/BooleanExpr.scala
- app/uk/gov/hmrc/gform/services/SubmissionService.scala
- test/uk/gov/hmrc/gform/models/BooleanExprSpec.scala
- test/uk/gov/hmrc/gform/models/SubmissionServiceSpec.scala
> Revert "Revert "remove fields from excluded sections from submission""

- app/uk/gov/hmrc/gform/TheApplicationModule.scala
- app/uk/gov/hmrc/gform/auditing/AuditingModule.scala
- app/uk/gov/hmrc/gform/config/config.scala
- app/uk/gov/hmrc/gform/fileUpload/FileUploadConnector.scala
- app/uk/gov/hmrc/gform/fileUpload/FileUploadFrontendConnector.scala
- app/uk/gov/hmrc/gform/fileUpload/FileUploadModule.scala
- app/uk/gov/hmrc/gform/fileUpload/model.scala
- app/uk/gov/hmrc/gform/theauditing/AuditingModule.scala
- app/uk/gov/hmrc/gform/time/TimeModule.scala
- app/uk/gov/hmrc/gform/wshttp/WSHttpModule.scala
- conf/application.conf
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/gform/Spec.scala
- test/uk/gov/hmrc/gform/config/AppConfigSpec.scala
- test/uk/gov/hmrc/gform/fileUpload/DemoApp.scala
- test/uk/gov/hmrc/gform/fileUpload/FileUploadConnectorSpec.scala
- test/uk/gov/hmrc/gform/time/FrozenTime.scala
- test/uk/gov/hmrc/gform/wshttp/StubbedWSHttp.scala
> introduction to implicit less dependency injection and encapsulated modules

- app/uk/gov/hmrc/gform/connectors/Save4LaterConnector.scala
- app/uk/gov/hmrc/gform/controllers/FormController.scala
- app/uk/gov/hmrc/gform/models/Form.scala
- app/uk/gov/hmrc/gform/services/FormService.scala
- app/uk/gov/hmrc/gform/typeclasses/Delete.scala
- conf/app.routes
Fixing the error when choosing the delete option
> enabled the delete functionality for the save4 later

- app/uk/gov/hmrc/gform/models/FieldId.scala
> changing the . to - in fieldId

- app/uk/gov/hmrc/gform/fileupload/FileUploadService.scala
- app/uk/gov/hmrc/gform/sharedmodel/config/ContentType.scala
- it/uk/gov/hmrc/gform/ExposedConfigSpec.scala
- test/uk/gov/hmrc/gform/config/AppConfigSpec.scala
- test/uk/gov/hmrc/gform/fileupload/ExampleFileUploadData.scala
- test/uk/gov/hmrc/gform/fileupload/FileUploadDemoApp.scala
- test/uk/gov/hmrc/gform/fileupload/HelperSpec.scala
More extensive fix of file upload content type so that all works and tests pass
> More extensive fix of file upload content type

- it/uk/gov/hmrc/gform/PingSpec.scala
- it/uk/gov/hmrc/gform/TemplatesInSampleDataSpec.scala
- it/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
- it/uk/gov/hmrc/gform/support/ITSpec.scala
- it/uk/gov/hmrc/gform/wshttp/TestWSHttp.scala
Upload template test is failing with:
java.lang.NoSuchMethodError: uk.gov.hmrc.gform.repo.Repo.collection()Lreactivemongo/json/collection/JSONCollection;
at uk.gov.hmrc.gform.repo.Repo.upsert(Repo.scala:49)
So disabled it
> Dave/gfc 75/great library upgrade it tests

- app/uk/gov/hmrc/gform/fileupload/FileUploadService.scala
- app/uk/gov/hmrc/gform/fileupload/MetadataXml.scala
- app/uk/gov/hmrc/gform/submission/SectionFormField.scala
- app/uk/gov/hmrc/gform/submission/SubmissionService.scala
- sample-data/EEITTTestUsers.txt
- test/uk/gov/hmrc/gform/sharedmodel/MetadataXmlSpec.scala
- test/uk/gov/hmrc/gform/submission/SectionFormFieldSpec.scala
Calculate attachment count in the DMS submission metadata, based on number of file fields with files in the submission
> Dave/gfc 102/attachment count

- app/uk/gov/hmrc/gform/submission/SectionFormField.scala
- app/uk/gov/hmrc/gform/submission/SubmissionService.scala
Do not count files that have not been uploaded for the DMS attachment count
> Do not count files that have not been uploaded

- app/uk/gov/hmrc/gform/playcomponents/PlayComponentsModule.scala
Accept prod.Routes as normal and gerenerate only one Router, rather than two
> Accept prod.Routes as normal and gerenerate only one Router

- app/uk/gov/hmrc/gform/core/parsers/BooleanExprParser.scala
- test/uk/gov/hmrc/gform/core/parsers/BooleanExprParserSpec.scala
GFC-587 Fix bugs in boolean expression parsing, evaluating left to right and brackets working as expected
> Fix bugs in boolean expression parsing

- app/uk/gov/hmrc/gform/repo/Repo.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/DraftRetrievalMethod.scala
- app/uk/gov/hmrc/gform/sharedmodel/graph/DependecyGraph.scala
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/gform/core/parsers/ValueParserSpec.scala
- test/uk/gov/hmrc/gform/services/SubmissionServiceSpec.scala
> GFC-596 Allow changes to calculations if selections change.

- app/uk/gov/hmrc/gform/testonly/TestOnlyController.scala
- conf/application.conf
- conf/testOnlyDoNotUseInAppConf.routes
Remove stub implementation from gform and connect to gform-stubs
> Dave/gfc 675/add gform stubs

- app/uk/gov/hmrc/gform/sharedmodel/ValueClassFormat.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormComponentId.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormComponentGen.scala
At the top of the FormComponentId case class, the method withSuffix creates a string using a hypen. Does this cause any problems I need to address?
> Lg/gfc755/disable hyphen in field id's

- app/uk/gov/hmrc/gform/core/FormValidator.scala
- app/uk/gov/hmrc/gform/core/parsers/ValueParser.scala
- app/uk/gov/hmrc/gform/formtemplate/FormTemplateService.scala
- app/uk/gov/hmrc/gform/formtemplate/FormTemplateValidator.scala
- app/uk/gov/hmrc/gform/formtemplate/FormTemplatesController.scala
- app/uk/gov/hmrc/gform/formtemplate/FormTemplatesControllerRequestHandler.scala
- app/uk/gov/hmrc/gform/formtemplate/Verifier.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/Expr.scala
- test/uk/gov/hmrc/gform/core/FormValidatorSpec.scala
- test/uk/gov/hmrc/gform/core/TemplateValidatorSpec.scala
- test/uk/gov/hmrc/gform/core/parsers/ValueParserSpec.scala
- test/uk/gov/hmrc/gform/formtemplate/FormTemplatesControllerRequestHandlerTest.scala
Extract upsert request logic in to a handler
Request handler test
refactoring => use generic type
refactoring => final tagless
Add unhappy path test
Remove useless inheritance
Remove unused class
Add a form template validator
Add enrolment validation wiring +  test
Refactoring => remove some duplication from test
unused import
Remove unused code
Extract trit verifier
> Pas 712 Support ${user.enrolledIdentifier} 

- app/uk/gov/hmrc/gform/sharedmodel/form/SubmissionData.scala
- app/uk/gov/hmrc/gform/submission/DestinationsSubmitter.scala
- app/uk/gov/hmrc/gform/submission/SubmissionController.scala
- app/uk/gov/hmrc/gform/submission/SubmissionService.scala
- app/uk/gov/hmrc/gform/submission/handlebars/HandlebarsTemplateProcessorModel.scala
- project/Dependencies.scala
- project/plugins.sbt
- test/pact/uk/gov/hmrc/gform/GFormConnectorVerifiersPactSpec.scala
- test/uk/gov/hmrc/gform/submission/DestinationSubmissionInfoGen.scala
Just a renaming
Add Variables to DestinationInfo (not tested yet!)
for Lance to be checked
Wire in Variables to handlebar
Ignore pact
> SubmissionData from frontend

- app/uk/gov/hmrc/gform/ApplicationLoader.scala
- app/uk/gov/hmrc/gform/form/FormModule.scala
- app/uk/gov/hmrc/gform/submission/SubmissionModule.scala
- delivered_pacts/gform-frontend_gform.json
- docker-compose.yml
- pacts/Consumer_Provider.json
- pacts/myPact.json
- test/pact/uk/gov/hmrc/gform/GFormConnectorVerifiersPactSpec.scala
- test/pact/uk/gov/hmrc/gform/StubServer.scala
Just a renaming
Add Variables to DestinationInfo (not tested yet!)
for Lance to be checked
Wire in Variables to handlebar
Ignore pact
Working on progress
Working toward a stubbed server => do not look pretty at the moment but serves http reqs
Add docker to spin up save4Later stub
Add file uploader stub + mongo
Add pact stubber jar
mv pact jar into different folder
Add save4later stubbed service
This succeed on http://localhost:9196/gform/forms/123 with sm & gform running
Fix find form ID 123
finally worked end to end!
cleaning up started - private def createPdfSummary neeeds to be fixed + running up port
pdf file stubbing => green test!
cleaning up step#1
Add get template test
Remove local path to mongo data
Fix conflict
> Contract testing

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormatExpr.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormatExprGen.scala
an unused variable was found while working on handlebars tests, removed as lanced requested.
> [no-GFC][DC] removed unused variable

- app/uk/gov/hmrc/gform/fileupload/FileUploadService.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Destination.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Destinations.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/HandlebarsTemplateProcessorModel.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/JsonStructuredFormDataBuilder.scala
- app/uk/gov/hmrc/gform/structuredform/FieldName.scala
- app/uk/gov/hmrc/gform/structuredform/RoboticsXMLGenerator.scala
- app/uk/gov/hmrc/gform/structuredform/StructuredFormDataBuilder.scala
- app/uk/gov/hmrc/gform/structuredform/StructuredFormValue.scala
- app/uk/gov/hmrc/gform/submission/PdfAndXmlSummariesFactory.scala
- app/uk/gov/hmrc/gform/submission/Submission.scala
- app/uk/gov/hmrc/gform/submission/SubmissionService.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/JsonStructuredFormDataBuilderSpec.scala
- test/uk/gov/hmrc/gform/structuredform/RoboticsXMLGeneratorSpec.scala
- test/uk/gov/hmrc/gform/structuredform/StructuredFormDataBuilderSpec.scala
Unit tests fixed for new type
Refactored
added seqNum for array entries
Added test for repeating sections
added xml submission
renamed roboticsXML to includeRoboticsXml
refactored JsonRestructuredFormBuilder
> GFC-833/David/XML

- app/uk/gov/hmrc/gform/core/FormValidator.scala
- app/uk/gov/hmrc/gform/formtemplate/FormComponentMaker.scala
- app/uk/gov/hmrc/gform/formtemplate/FormComponentMakerService.scala
- app/uk/gov/hmrc/gform/formtemplate/FormTemplateValidator.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ComponentType.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/HasExpr.scala
- app/uk/gov/hmrc/gform/submission/SubmissionServiceHelper.scala
- test/uk/gov/hmrc/gform/sharedmodel/FormComponentSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/JsonParseTestFormat.scala
- test/uk/gov/hmrc/gform/sharedmodel/JsonParseTestValue.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormComponentMakerServiceSpec.scala
the json now has the variable of toUpperCase and the code has been refactored in an attempyt to group data types together.
> Lg/gfc 856/to upper case property/attempt2 improve

- app/uk/gov/hmrc/gform/fileupload/FileUploadFrontendConnector.scala
- app/uk/gov/hmrc/gform/fileupload/Helper.scala
- test/uk/gov/hmrc/gform/fileupload/RetryingSpec.scala
* [DC-1947] Implement upload retry functionality.
> [DC-1947] Implement upload retry functionality. (#449)

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/Expr.scala
- test/uk/gov/hmrc/gform/core/parsers/ValueParserSpec.scala
Complete rewrite of Else expression
> GFC-911 - orElse expression operator to permit return of first valid value

- conf/app.routes
User is unable to save or print the PDF after successful submission
> GFC-1124 - BAU Live Support

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Destination.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/UploadableDestinationSpec.scala
Converted single quotes in formData field, in submissionConsolidator destination
> Converted single quotes in formData field, in submissionConsolidator destination

- app/uk/gov/hmrc/gform/core/parsers/BasicParsers.scala
For example: "${!legalStatus = 1} "
> Parse expressions followed by whitespaces

- app/uk/gov/hmrc/gform/ApplicationLoader.scala
- app/uk/gov/hmrc/gform/notifier/NotifierModule.scala
- app/uk/gov/hmrc/gform/notifier/NotifierService.scala
- app/uk/gov/hmrc/gform/proxy/ProxyModule.scala
GOV.UK Notify outbound calls needs to use proxy
> GFORMS-1029 - Gforms Notify email live issue

- app/uk/gov/hmrc/gform/formtemplate/FormTemplateValidator.scala
- app/uk/gov/hmrc/gform/formtemplate/SectionHelper.scala
- test/uk/gov/hmrc/gform/core/TemplateValidatorSpec.scala
List items to be displayed
Allow ${addAnother.count} expression in value field
> GFORMS-1076 - Add a new expression to allow for the count of Add to

- app/uk/gov/hmrc/gform/formtemplate/Rewriter.scala
- test/resources/templates-to-reject/component-level-include-if.json
- test/uk/gov/hmrc/gform/sharedmodel/FormComponentRejectSpec.scala
Rewrite includeIf on form component level
> GFORMS-383 - Introduce IncludeIf functionality at field level

- app/uk/gov/hmrc/gform/envelope/EnvelopeController.scala
Fixed log issue - envelope for given id:  not found
> GFORMS-2184 - Sprint 95 release activities

- app/uk/gov/hmrc/gform/formtemplate/FormTemplatesController.scala
- app/uk/gov/hmrc/gform/playcomponents/ErrorHandler.scala
- app/uk/gov/hmrc/gform/sharedmodel/LatestFormTemplateNotFoundException.scala
- Changed the logger level from ERROR to WARN
> GFORMS-2341 - Sprint 102 release activities

- conf/formTemplateSchema.json
- Added `onePerUser` draftRetrievalMethod into Json schema
> GFORMS-2343 - Sprint 104 release activities

- app/uk/gov/hmrc/gform/formtemplate/ConditionalValidationRequirement.scala
- app/uk/gov/hmrc/gform/formtemplate/JsonSchemeValidator.scala
- conf/formTemplateSchema.json
- test/uk/gov/hmrc/gform/formtemplate/JsonSchemeValidatorSpec.scala
Adds the conditional validation checks for the format property.
Also adds test cases for different fields in the same section since should be covered.
> GFORMS-2550: Conditional Validation for the Format Property

- app/uk/gov/hmrc/gform/core/parsers/FormatParser.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormatExpr.scala
GFORMS-2952 - Add new register for local authority
GFORMS-2927 - Add new register for trade sectors
> GFORMS-2952 and GFORMS-2927

- app/uk/gov/hmrc/gform/sharedmodel/form/VisitIndex.scala
- test/uk/gov/hmrc/gform/sharedmodel/form/VisitIndexSuite.scala
Handle potential rollback for tasklist
> GFORMS-3005 - Refactor SectionNumber to be more predictable
